### PR TITLE
Newsweek-clone 

### PR DESCRIPTION
**Pull request by jstloyal**
# Newsweek-C
Newsweek clone-desktop-view
lone

> What the project is about
-Using bootstrap to create a responsive website

> How the project was done

The Layout shows the basic structure of the page using empty semantic HTML elements that are appropriately sized and positioned. 
Used Bootstrap4 for the page layout
Use bootstrap for the responsiveness of the page
Add some media Query to make it more responsive

## Built With

- HTML, CSS
- Bootstrap
- VS-code

## Live Demo

[Live Demo Link](https://rawcdn.githack.com/jstloyal/Newsweek-Clone/0f4252e9c9deb97e61ace339cdcf0e839567ff9b/index.html)

## Getting Started

To get a local copy up and running follow these simple example steps.

### Prerequisites
- Web browser
- Code editor
- Git and Github

### Usage
- Clone the project to your local machine 
- Open the index file in your browser

## Authors

- Adetayo Sunkanmi

👤 **Author1**

- Github: [Adetayo Sunkanmi](https://github.com/jstloyal)
- Twitter: [Adetayo Sunkanmi](https://twitter.com/jstloyalty)
- Linkedin: [Adetayo Sunkanmi](https://www.linkedin.com/in/jstloyalty/)

## 🤝 Contributing

Feel free to check the [issues page](https://github.com/jstloyal/Newsweek-Clone/issues).

Contributions, issues and feature requests are welcome!

Start by:
* Forking the project
* Cloning the project to your local machine
* `cd` into the project directory
* Run `git checkout -b your-branch-name`
* Make your contributions
* Push your branch up to your forked repository
* Open a Pull Request with a detailed description to the development branch of the original project for a review

## Show your support

Give a ⭐️ if you like this project!

## Acknowledgments

- Google

## 📝 License

This project is [MIT](lic.url) licensed.

### CODE REVIEW

**Review by men32z — COMMENTED** [review]
## Pull request currently under review by Luis Preza (TSE).

Kindly exercise patience 🐱

**Review by men32z — CHANGES_REQUESTED** [review]
Hey @jstloyal !
## Good job on this project, great Readme file, you did great with the responsiveness! 👍

good job with bootstrap although you could use a little more since it is a bootstrap project.

There are still some changes 👇 you need to implement to approve this request 🔍

### Required changes
* [x] please fix the navbar on mobile devices 
#### original
Screenshot_2020-03-26 Newsweek(1)
#### yours
Screenshot_2020-03-26 Newsweek clone(1)

* [x] kindly fix the footer on mobile version.
#### original 
Screenshot_2020-03-26 Newsweek

#### yours
Screenshot_2020-03-26 Newsweek clone

* [x] the opinion section author's images aren't aligned with the text in the mobile version, kindly fix this issue
#### original 
Screenshot_2020-03-26 Newsweek(2)
#### yours
Screenshot_2020-03-26 Newsweek clone(2)


* [x] some images in mobile version are distorted
Screenshot_2020-03-26 Newsweek clone(3)


* [x] articles images are taking all div with in mobile version
Screenshot_2020-03-26 Newsweek clone(4)

### Optional
* [x] [OPTIONAL] take a general look on the mobile version. to improve the little details in the project

You did great in the wide version and I'm sure you can fix these required changes, keep working as hard as you're doing!


## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@men32z)
I would be happy to help! 👩‍💻

Happy coding 🤓

--Luis Preza

**Comment by men32z** [comment]
* [x] [REQUIRED] I forgot to tell you that all stickler's checks must pass

**Comment by thsvr** [comment]
### **STATUS: PROJECT APPROVED** :1st_place_medal: :1st_place_medal: :1st_place_medal: 

Hi @jstloyal :smile: :smile: 

You did all the required changes asked by Luis (TSE) and now your project looks beautiful and professional, congrats for the hard work :smiley_cat: :smiley_cat: 

Before merge it to master, can you please update your demo live link on the readme? 

If you have any questions, don't hesitate to contact me through slack [@Thaís Vieira Azevedo](url)


### Happy coding and good luck on the next project :computer: 

_Project reviewed by Thaís Vieira (TSE)_

**Comment by thsvr** [comment]
ps. I'm seeing that you are doing changes after request the review and it is not recommended. Next time, can you please do all the changes before you send the project for review? Or if you realize that you need to change something, it is recommended you to wait for the review finish and then you can do the changes :smiley_cat: :smile_cat:

**Pull request merged**
